[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "pyoptinterface"
version = "0.2.8"
description = "Python interface to multiple optimization solvers"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Yue Yang", email = "metab0t@outlook.com" }]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering',
    'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
]

[project.urls]
Homepage = "https://github.com/metab0t/pyoptinterface"

[project.optional-dependencies]
doc = ["sphinx", "myst-parser", "myst-nb", "sphinx-copybutton", "furo", "numpy", "highsbox"]
test = ["pytest", "numpy"]
highs = ["highsbox"]
nlp = ["llvmlite", "tccbox"]

[tool.scikit-build]
editable.rebuild = true
build-dir = "build/{wheel_tag}"
cmake.build-type = "Release"

[tool.scikit-build.cmake.define]
PYTHON_VERSION = { env = "PYTHON_VERSION", default = "3.8" }
CMAKE_FIND_DEBUG_MODE = "OFF"
ENABLE_TEST_MAIN = "OFF"

[tool.cibuildwheel]
test-command = 'python -c "import pyoptinterface as poi; print(dir(poi))"'
build = "*-manylinux_x86_64 *-manylinux_aarch64 *-win_amd64 *-macosx_x86_64 *-macosx_arm64"
skip = "cp36-* cp37-* pp* cp38-macosx_arm64"
archs = "native"
manylinux-x86_64-image = "quay.io/pypa/manylinux2014_x86_64"
manylinux-aarch64-image = "quay.io/pypa/manylinux2014_aarch64"
[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
[tool.cibuildwheel.macos]
environment = { MACOSX_DEPLOYMENT_TARGET = "10.14" }
