name: "Install optimizers on linux"

inputs:
  GUROBI_WLS: 
    description: "..."
    required: true
  COPT_CLIENT_INI:
    description: "..."
    required: true
  MOSEK_LICENSE:
    description: "..."
    required: true
  GITHUB_TOKEN:
    description: "..."
    required: true
  CHECK_LICENSE: 
    description: "..."
    required: true
  ARCH:
    description: "..."
    required: true
    type: choice
    default: "X64"
    options:
      - "X64"
      - "ARM64"

runs:
  using: "composite"
  steps:
    - name: Create directory to store installers
      shell: bash
      run: |
        mkdir -p ~/installers

    - name: Cache Installers
      id: cache-installers-linux
      uses: actions/cache@v4
      env:
        cache-name: cache-installers-linux
      with:
        path: ~/installers
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('optimizer_version.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - if: ${{ steps.cache-installers-linux.outputs.cache-hit != 'true' && inputs.ARCH == 'X64' }}
      shell: bash
      name: Download Installers
      run: |
        curl -L -o ~/installers/gurobi.tar.gz https://packages.gurobi.com/11.0/gurobi11.0.0_linux64.tar.gz
        curl -L -o ~/installers/copt.tar.gz https://pub.shanshu.ai/download/copt/7.1.4/linux64/CardinalOptimizer-7.1.4-lnx64.tar.gz
        curl -L -o ~/installers/mosek.tar.bz2 https://download.mosek.com/stable/10.2.0/mosektoolslinux64x86.tar.bz2

    - if: ${{ steps.cache-installers-linux.outputs.cache-hit != 'true' && inputs.ARCH == 'arm64' }}
      shell: bash
      name: Download Installers
      run: |
        curl -L -o ~/installers/gurobi.tar.gz https://packages.gurobi.com/11.0/gurobi11.0.3_armlinux64.tar.gz
        # TODO fix copt link
        curl -L -o ~/installers/copt.tar.gz https://pub.shanshu.ai/download/copt/7.1.4/linuxarm64/CardinalOptimizer-7.1.4-lnxarm64.tar.gz
        curl -L -o ~/installers/mosek.tar.bz2 https://download.mosek.com/stable/10.2.3/mosektoolslinuxaarch64.tar.bz2

    - name: Setup Gurobi Installation
      shell: bash
      env:
        GUROBI_WLS: ${{ inputs.GUROBI_WLS }}
      run: |
        tar xfz ~/installers/gurobi.tar.gz -C ~/
        # set environment variables
        export GUROBI_HOME="${HOME}/gurobi1100/linux64"
        if [[ ${{ inputs.ARCH }} == "ARM64" ]]; then
          export GUROBI_HOME="${HOME}/gurobi1100/armlinux64"
        fi
        echo "GUROBI_HOME=${GUROBI_HOME}" >> $GITHUB_ENV
        echo "PATH=${PATH}:${GUROBI_HOME}/bin" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib" >> $GITHUB_ENV
        echo $GUROBI_HOME
        ls $GUROBI_HOME

        # setup license using secrets
        echo "$GUROBI_WLS" > ~/gurobi.lic
        echo "GRB_LICENSE_FILE=${HOME}/gurobi.lic" >> $GITHUB_ENV
    - name: Test Gurobi
      if: ${{ inputs.CHECK_LICENSE == 'true' }}
      shell: bash
      run: |
        gurobi_cl

    - name: Setup COPT Installation
      shell: bash
      env:
        COPT_CLIENT_INI: ${{ inputs.COPT_CLIENT_INI }}
      run: |
        tar xfz ~/installers/copt.tar.gz -C ~/
        ls ~/copt71
        # set environment variables
        export COPT_HOME="${HOME}/copt71"
        echo "COPT_HOME=${COPT_HOME}" >> $GITHUB_ENV
        echo "PATH=${PATH}:${COPT_HOME}/bin" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${COPT_HOME}/lib" >> $GITHUB_ENV
        echo $COPT_HOME

        # Just use the size-limited license
        # echo "$COPT_CLIENT_INI" > ~/client.ini
        # echo "COPT_LICENSE_DIR=${HOME}" >> $GITHUB_ENV
    - name: Test COPT
      if: ${{ inputs.CHECK_LICENSE == 'true' }}
      shell: bash
      run: |
        copt_cmd -c "quit"

    - name: Setup MOSEK Installation
      shell: bash
      env:
        MOSEK_LICENSE: ${{ inputs.MOSEK_LICENSE }}
      run: |
        tar jxf ~/installers/mosek.tar.bz2 -C ~/
        ls ~/mosek
        # set environment variables
        export MOSEK_10_2_BINDIR="${HOME}/mosek/10.2/tools/platform/linux64x86/bin"
        if [[ ${{ inputs.ARCH }} == "ARM64" ]]; then
          export MOSEK_10_2_BINDIR="${HOME}/mosek/10.2/tools/platform/linuxaarch64/bin"
        fi
        echo "MOSEK_10_2_BINDIR=${MOSEK_10_1_BINDIR}" >> $GITHUB_ENV
        echo "PATH=${PATH}:${MOSEK_10_2_BINDIR}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MOSEK_10_2_BINDIR}" >> $GITHUB_ENV
        echo $MOSEK_10_2_BINDIR

        # setup license using secrets
        echo "$MOSEK_LICENSE" > ~/mosek.lic
        echo "MOSEKLM_LICENSE_FILE=${HOME}/mosek.lic" >> $GITHUB_ENV
    - name: Test MOSEK
      if: ${{ inputs.CHECK_LICENSE == 'true' }}
      shell: bash
      run: |
        msktestlic
